
flowchart TB

    X["Define:<br><br>x = ...9999"]
    SHIFT["Shift left one digit:<br><br>10x = ...99990"]
    SUB["Subtract:<br><br>(10x) − x = ...99990 − ...9999 = −1"]
    SOLVE["Therefore:<br><br>9x = −1"]
    RESULT["Conclusion:<br><br>x = −1"]

    X --> SHIFT --> SUB --> SOLVE --> RESULT
